# Imagen base oficial de Node
FROM node:18

# Crear directorio de la app
WORKDIR /usr/src/app

# Copiar package.json y package-lock.json
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el resto del código
COPY . .

# Exponer puerto de la app
EXPOSE 3000

# Comando de inicio
CMD ["node", "src/index.js"]
